# -*- coding: utf-8 -*-
"""notebook_다른데이터.ipynb의 사본의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_lpSwgLzl9JxyWElcBNHi0GL9QYNZgD9

# Notebook 6 — Toward a Tiny GPT

이제 남은 모듈들을 하나씩 추가하여 **좀 더 GPT다운 구조**로 갑니다.

이번 노트북에서 추가하는 것들:

- multi-head attention
- feedforward network
- residual connection
- layer normalization
- block stacking
"""

!pip install datasets -q

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from pathlib import Path
from datasets import load_dataset
from itertools import islice

# 기존에 잘못 생성된 파일이 있으면 삭제
if Path("input.txt").exists():
    Path("input.txt").unlink()

# TinyStories 일부만 스트리밍으로 가져오기
ds = load_dataset(
    "roneneldan/TinyStories",
    split="train",
    streaming=True
)

stories = []
for row in islice(ds, 1000):   # 처음 1000개만 사용
    stories.append(row["text"])

with open("input.txt", "w", encoding="utf-8") as f:
    f.write("\n\n".join(stories))

text = open("input.txt", "r", encoding="utf-8").read()
chars = sorted(list(set(text)))  # set:중복제거 #list:리스트로 변경 # sorted:정렬
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for ch, i in stoi.items()}
vocab_size = len(chars)
data = torch.tensor([stoi[ch] for ch in text], dtype=torch.long)

class NextTokenDataset(Dataset):
    def __init__(self, data, block_size):
        self.data = data
        self.block_size = block_size
    def __len__(self):
        return len(self.data) - self.block_size  # 몇개의 학습 샘플을 생성할 수 있는지
    def __getitem__(self, idx):
        x = self.data[idx : idx + self.block_size]  # idx부터 idx+self.block_size까지
        y = self.data[idx + 1 : idx + self.block_size + 1]
        return x, y

block_size = 64
dataset = NextTokenDataset(data, block_size)
loader = DataLoader(dataset, batch_size=64, shuffle=True)
xb, yb = next(iter(loader))  # iter:DataLoader 반복자 생성 #next:첫 배치 꺼내기 #shape:torch.Size([batch_size,block_size])

text

"""## 1. Multi-head attention


"""

class Head(nn.Module):  # 하나의 Attention Head를 의미
    def __init__(self, emb_dim, head_size, block_size, dropout=0.1):
        super().__init__()
        self.key = nn.Linear(emb_dim, head_size, bias=False) # emb_dim을 head_size로 바꾼다
        self.query = nn.Linear(emb_dim, head_size, bias=False)
        self.value = nn.Linear(emb_dim, head_size, bias=False)
        self.register_buffer("tril", torch.tril(torch.ones(block_size, block_size))) #모든 원소가 1인 행렬 생성하여 하삼각행렬로 만든다.
                                                                                     # register_buffer를 사용한 이유는 모델을 GPU로 옮길 때 tril도 같이 옮기기 위해
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B, T, C = x.shape # if x.shape=(64,64,384), B=64, T=64, C=384, 64개의 문장, 64개의 토큰, 384차원 임베딩
        k = self.key(x) # (64,64,384)->(64,64,64)
        q = self.query(x)
        v = self.value(x)
        wei = q @ k.transpose(-2, -1) * (k.size(-1) ** -0.5) # k.transpose(-2, -1)은 두 자리 바꾸기로 @있는 행렬은 현재 단어가 다른 단어를 얼마나 참고할지를 의미(attention score).
                                                             # 곱하기 뒤에는 큰 차원에서는 내적값이 너무 커지기에(scaling)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float("-inf")) # Masking: 행렬에서 위 삼각형을 0으로 만들고 -inf로 만든다. 미래 정보를 제거하기 위해 사용
        wei = F.softmax(wei, dim=-1) # 총 합이 1이되도록 확률을 계산해준다. -inf인 위치는 0 확률이 된다.
        wei = self.dropout(wei) # 과적합 방지를 위해 일부 attention weight를 랜덤하게 제거
        out = wei @ v # attention 가중치 x value
        return out

class MultiHeadAttention(nn.Module):
    def __init__(self, emb_dim, num_heads, block_size, dropout=0.1):
        super().__init__()
        head_size = emb_dim // num_heads
        self.heads = nn.ModuleList([Head(emb_dim, head_size, block_size, dropout) for _ in range(num_heads)]) # head 여러개 생성
        self.proj = nn.Linear(emb_dim, emb_dim)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1) # torch.cat은 차원을 연결. 즉 더하기를 해준다. dim=-1이므로 마지막 차원 덧셈
        out = self.proj(out) # 각 head의 정보를 섞어주기 위해
        out = self.dropout(out)
        return out

"""## 2. Feedforward + Block"""

class FeedForward(nn.Module): # MLP
    def __init__(self, emb_dim, dropout=0.1):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(emb_dim, 4 * emb_dim), # 차원을 4배 늘린다.
            nn.ReLU(),   # 음수를 0으로 만든다
            nn.Linear(4 * emb_dim, emb_dim), # 4배가 된 차원을 원래 차원으로 축소한다.
            nn.Dropout(dropout),
        )
    def forward(self, x):
        return self.net(x)

class Block(nn.Module): # transformer의 한 layer를 의미
    def __init__(self, emb_dim, num_heads, block_size, dropout=0.1):
        super().__init__()
        self.ln1 = nn.LayerNorm(emb_dim) # 각 토큰의 feature를 정규화. 비슷한 스케일로 맞춤.
        self.sa = MultiHeadAttention(emb_dim, num_heads, block_size, dropout)
        self.ln2 = nn.LayerNorm(emb_dim)
        self.ffwd = FeedForward(emb_dim, dropout)

    def forward(self, x):
        x = x + self.sa(self.ln1(x)) # residual connection : 원래 정보+ 새로운 정보. Attention은 토큰 끼리 정보를 주고 받는다.
        x = x + self.ffwd(self.ln2(x)) # feedforward는 각 토큰의 표현력 강화
        return x

"""## 3. Tiny GPT"""

class TinyGPT(nn.Module):
    def __init__(self, vocab_size, block_size, emb_dim=128, num_heads=4, num_layers=4, dropout=0.1):
        super().__init__()
        self.token_embedding = nn.Embedding(vocab_size, emb_dim) # 65개의 문자를 128차원 벡터로 바꾸는 것
        self.position_embedding = nn.Embedding(block_size, emb_dim) # 순서 정보가 없기에 64개 각각의 위치에 대한 벡터 학습
        self.blocks = nn.Sequential(*[
            Block(emb_dim, num_heads, block_size, dropout) for _ in range(num_layers)
        ])
        self.ln_f = nn.LayerNorm(emb_dim)
        self.lm_head = nn.Linear(emb_dim, vocab_size) # 각 문자에 대한 점수를 만들기 위해

    def forward(self, x):
        B, T = x.shape
        pos = torch.arange(T, device=x.device) # tensor([0,1,2,....,63])
        tok = self.token_embedding(x)
        pos = self.position_embedding(pos)[None] # 차원을 맞춰주기 위해 (64,128) -> (1,64,128)
        h = tok + pos # Broadcasting 때문에 (64,64,128)
        h = self.blocks(h)
        h = self.ln_f(h)
        logits = self.lm_head(h) # (64,64,65)
        return logits

model = TinyGPT(vocab_size, block_size)
logits = model(xb)
print("logits.shape:", logits.shape) # batch_size, block_size, vocab_size

"""## 4. 학습"""

def sequence_cross_entropy(logits, targets):
    return F.cross_entropy(logits.transpose(1, 2), targets) # F.cross_entropy는 class 차원이 두 번째에 있어야 하기에 바꿔주고 이를 targets과 비교한다. 각 위치마다 65개의 문자 중 정답 문자를 맞히는 loss 계산

def train_one_epoch(model, loader, optimizer, device, max_steps=None):
    model.train()
    total_loss, total_count = 0.0, 0
    for step, (xb, yb) in enumerate(loader):
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        loss = sequence_cross_entropy(logits, yb) # 모델 예측값 logits와 정답 yb를 비교. loss가 작을수록 모델이 다음 문자를 잘 맞히는 것. 처음에는 보통 loss가 크고, 학습할수록 작아진다.
        optimizer.zero_grad()
        loss.backward() # gradient 계산
        optimizer.step() # 계산된 gradient를 이용해 모델의 가중치 업데이트
        total_loss += loss.item() * xb.size(0) # batch별 평균 loss 곱하기 batch size
        total_count += xb.size(0)
        if max_steps is not None and step + 1 >= max_steps: # 한 반복마다 최대 max_steps번의 업데이트만 함
            break
    return total_loss / total_count # 한 epoch 동안의 평균 loss

device = "cuda" if torch.cuda.is_available() else "cpu"
model = TinyGPT(vocab_size, block_size).to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4)

for epoch in range(50):
    train_loss = train_one_epoch(model, loader, optimizer, device, max_steps=300)
    print(f"epoch {epoch:2d} | train loss {train_loss:.4f}")

"""## 5. Sampling"""

@torch.no_grad() # 생성할 때는 예측만 하면 되기에 gradient 계산은 끈다.
def sample_gpt(model, block_size, stoi, itos, device, start_text="Once upon a time", max_new_tokens=400):
    model.eval()
    context = torch.zeros((1, block_size), dtype=torch.long, device=device)
    for ch in start_text:
        if ch in stoi:
            ix = torch.tensor([[stoi[ch]]], device=device)
            context = torch.cat([context[:, 1:], ix], dim=1)
    out = list(start_text)
    for _ in range(max_new_tokens):
        logits = model(context)
        logits = logits[:, -1, :]
        probs = F.softmax(logits, dim=-1)
        ix = torch.multinomial(probs, num_samples=1)
        out.append(itos[ix.item()])
        context = torch.cat([context[:, 1:], ix], dim=1)
    return "".join(out)

print(sample_gpt(model, block_size, stoi, itos, device, start_text="Once upon a time", max_new_tokens=500))

"""## 6. 정리

이제 아주 작은 GPT 구조가 완성되었습니다.

전체 흐름은 다음과 같습니다.

1. bigram
2. MLP on names
3. MLP on Shakespeare
4. GPT-style dataset + minimal sequence model
5. single-head masked self-attention
6. tiny GPT
"""

