# -*- coding: utf-8 -*-
"""torch dataset의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5hxGCPWhMWrs3s6MJhaTepngvvdWceD

# Intro
"""

!wget https://raw.githubusercontent.com/karpathy/makemore/refs/heads/master/names.txt
# 깃허브 makemore에서 names.txt파일에 들어가 raw를 누르고 링크를 얻는다.

words = open("names.txt").read().splitlines()

chars = sorted(list(set("".join(words))))

chars = ["."] + chars

stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }

"""# Code from Lesson 2"""

import torch

# create the training set of bigrams (x,y)
xs, ys = [], []

for w in words[:]:
  chs = ['.'] + list(w) + ['.']  # list를 사용하는 이유는 코드를 읽기 쉽게 하기 위해서
  for ch1, ch2 in zip(chs, chs[1:]):  #zip은 남으면 버린다. ex) .emma.  emma.이기에 2묶음씩 묶어서 앞의 .이 남는데 이것은 버려진다.
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    #print(ch1, ch2)
    xs.append(ix1)
    ys.append(ix2)

xs = torch.tensor(xs)  # PyTorch의 신경망은 리스트가 아니라 텐서를 입력으로 받기에 텐서로 변경
ys = torch.tensor(ys)

xs

ys

"""# Code from Lesson 3"""

# build the dataset

block_size = 1 # 몇개의 문자를 가지고 다음 문자를 예측할지
X, Y = [], []
for w in words[:3]:

  print(w)
  context = [0] * block_size
  for ch in w + '.':  # ch에는 e가 들어가 있다. w의 첫번째 글자
    ix = stoi[ch]
    X.append(context)
    Y.append(ix)
    print(''.join(itos[i] for i in context), '--->', itos[ix])
    context = context[1:] + [ix] # crop and append

X = torch.tensor(X)
Y = torch.tensor(Y)

"""... -> e
..e -> m
.em -> m
emm -> a
mma -> .

... = 000 -> e =5
..e = 005
"""

X

Y

"""# New code"""

import torch
from torch.utils.data import Dataset, DataLoader

# --------------------------------------------------
# 1) names.txt 읽기
# --------------------------------------------------
words = open("names.txt", "r").read().splitlines()

# --------------------------------------------------
# 2) vocabulary 만들기
#    0번은 special token "." 로 고정
# --------------------------------------------------
chars = sorted(list(set("".join(words))))
if "." in chars:
    chars.remove(".")

chars = ["."] + chars

stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}

vocab_size = len(stoi)  # 데이터셋에 존재하는 서로 다른 문자들의 개수를 vocab_size에 넣기
pad_idx = 0   # "." 의 index

# --------------------------------------------------
# 3) words를 미리 정수 시퀀스로 변환
# --------------------------------------------------
encoded_words = [
    [stoi[ch] for ch in w]
    for w in words
]

encoded_words

# --------------------------------------------------
# 4) Dataset 정의
#    각 샘플:
#      x = 길이 block_size의 context
#      y = 다음 문자 1개
# --------------------------------------------------
class NamesContextDataset(Dataset):
    def __init__(self, encoded_words, block_size):
        self.X = []
        self.Y = []
        self.block_size = block_size

        for word in encoded_words:
            context = [0] * block_size   # 왼쪽 padding #왼쪽의 빈칸 채워주기

            # 마지막 종료 토큰 "." 추가
            for ix in word + [0]:
                self.X.append(context.copy())  # copy를 쓰는 이유는 모든 행이 같은 리스트를 참조할 수 있기에 안전하게 복사하려고
                self.Y.append(ix)
                context = context[1:] + [ix]

        self.X = torch.tensor(self.X, dtype=torch.long)  # long을 넣는 이유는 Embedding layer는 반드시 정수 인덱스를 입력받기 때문
        self.Y = torch.tensor(self.Y, dtype=torch.long)

    def __len__(self):
        return len(self.Y)

    def __getitem__(self, idx):
        return self.X[idx], self.Y[idx]

# --------------------------------------------------
# 5) Bigram용 dataset / dataloader
# --------------------------------------------------
bigram_dataset = NamesContextDataset(
    encoded_words=encoded_words,
    block_size=1
)

bigram_loader = DataLoader(
    bigram_dataset,
    batch_size=32,  # 한 번의 학습(step)에서 몇 개의 데이터를 동시에 사용할 것인가
    shuffle=True
)

# --------------------------------------------------
# 6) MLP용 dataset / dataloader
# --------------------------------------------------
mlp_dataset = NamesContextDataset(
    encoded_words=encoded_words,
    block_size=3
)

mlp_loader = DataLoader(
    mlp_dataset,
    batch_size=32,
    shuffle=True
)

for i in bigram_dataset[:10]:
    print(i)

# --------------------------------------------------
# 7) 확인용 출력 함수
# --------------------------------------------------
def show_samples(dataset, itos, n=5):
    for i in range(n):
        x, y = dataset[i]
        x_chars = [itos[j.item()] for j in x]
        y_char = itos[y.item()]
        print(f"{x_chars} -> {y_char}")

print("=== Bigram samples ===")
show_samples(bigram_dataset, itos, n=5)

print("\n=== MLP samples ===")
show_samples(mlp_dataset, itos, n=5)

# --------------------------------------------------
# 8) batch shape 확인
# --------------------------------------------------
xb_bigram, yb_bigram = next(iter(bigram_loader))
xb_mlp, yb_mlp = next(iter(mlp_loader))

print("\n=== Batch shapes ===")
print("Bigram x:", xb_bigram.shape)  # (32, 1)
print("Bigram y:", yb_bigram.shape)  # (32,)

print("MLP x:", xb_mlp.shape)        # (32, 3)
print("MLP y:", yb_mlp.shape)        # (32,)

